services:
  app:
    build: .
    container_name: lavanderia_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - vite

  vite:
    image: node:20
    container_name: lavanderia_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
